name: Telegram Issue Reply Notifications

on:
  issue_comment:
    types:
      - created

jobs:
  notify-reply:
    uses: jobmetric/github-notify/.github/workflows/telegram-issue-reply-notify.yml@master
    with:
      date_format: jalali
      timezone: Asia/Tehran 
    secrets:
    bot_token: ${{ secrets.BOT_TOKEN }}
    chat_id: ${{ secrets.CHAT_ID }}

